.pep8speaks.yml

This PR introduces a `.pep8speaks` config file for `pep8speaks`.  Closes #133.

Config file for pep8speaks

---

README.md
docs/source/database.rst
docs/source/index.rst
docs/source/jwql_monitors.rst
docs/source/tests.rst
docs/source/utils.rst
environment.yml
jwql/database/database_interface.py
jwql/jwql_monitors/generate_preview_images.py
jwql/jwql_monitors/monitor_filesystem.py
jwql/utils/monitor_template.py
jwql/utils/preview_image.py
requirements.txt
setup.py

This PR makes several changes to the API docs, namely:
1. Adds headings before the individual module (addresses @laurenmarietta's suggestion in #180)
2. Adds some project description to ReadTheDocs home page (addresses #180)
3. Some formatting changes to make things look nicer
4. Added section on Issue Reporting/Feature Requests to `README.md`
5. Added some conditional imports to some modules to get around ReadTheDocs build issues (addresses #154).
Closes #154 
Closes #180

API Documentation Updates

---

jwql/website/apps/jwql/templates/instrument.html
jwql/website/apps/jwql/views.py

See issue #148 
I may need to change the link used for FGS - where is the specific documentation for that kept?

Added documentation button to instrument pages

---

jwql/jwql_monitors/monitor_mast.py
jwql/tests/test_monitor_mast.py
jwql/utils/constants.py
jwql/utils/monitor_template.py
jwql/utils/utils.py
jwql/website/apps/jwql/data_containers.py
jwql/website/apps/jwql/forms.py
jwql/website/apps/jwql/views.py
style_guide/style_guide.md

Add standards for instrument names and program IDs.

style guide: naming conventions

---

jwql/tests/test_api_views.py
jwql/tests/test_edb_interface.py

This PR attempts to get our tests actually running in our Jenkins builds.
Closes #262

Fix unit tests in Jenkins builds

---

jwql/website/apps/jwql/static/css/jwql.css
jwql/website/apps/jwql/templates/base.html

This is truly trivial, but something messed up the height of the navbar a few PRs back and it had been bothering me.
This PR just updates the padding of some objects on the navbar to bring its height back down to normal.

Fix padding of buttons on navbar

---

pytest.ini

Potential fix per @jhunkeler's instructions.

trying to make pytest results file jive with jenkins

---

jwql/website/apps/jwql/templates/base.html
jwql/website/apps/jwql/templates/instrument.html
jwql/website/apps/jwql/views.py

This addresses #236 and has documentation pages open in a new tab.

Documentation pages open in new tab

---

CHANGES.rst
setup.py

This PR updates `jwql` to version `0.18.0`.

Release 0.18.0

---

docs/source/tests.rst
jwql/tests/test_logging_functions.py

Tests for logging_functions

---

jwql/jwql_monitors/monitor_filesystem.py

This fixes some issues raised in Issue #386 
Y axis titles are now fixed and the color palette for the plotted lines have fewer repeating colors.

Fixed Filesystem Monitor plot y axis titles and colors

---

notebooks/edb_mnemonic_query.ipynb

Update notebook with new code structure and dependencies.
This PR should be addressed only after #402 has been merged.
Closes #362

Update edb notebook

---

jwql/edb/engineering_database.py
jwql/website/apps/jwql/data_containers.py
jwql/website/apps/jwql/oauth.py
jwql/website/apps/jwql/templates/engineering_database.html
jwql/website/apps/jwql/views.py

This PR introduces changes to the web app code that allow MAST authentication for EDB queries (and any other service provided by astroquery.mast) when the user has logged into the web app.
closes #329

Edb access via web app login

---

CHANGES.rst
setup.py

This PR updates jwql `develop` branch to version 0.20.0.
(Awaiting merge of #427.)

Release 0.20.0 [develop]

---

Jenkinsfile
jwql/database/database_interface.py
jwql/tests/test_api_views.py
jwql/tests/test_dark_monitor.py
jwql/tests/test_database_interface.py
jwql/tests/test_edb.py
jwql/tests/test_instrument_properties.py
jwql/tests/test_loading_times.py
jwql/tests/test_logging_functions.py
jwql/tests/test_permissions.py
jwql/tests/test_pipeline_tools.py
jwql/tests/test_preview_image.py
jwql/tests/test_utils.py

The Jenkins build is failing inexplicably: https://ssbjenkins.stsci.edu/blue/organizations/jenkins/STScI%2Fjwql/detail/bokeh_templating/1/pipeline/28
Trying to investigate.

Fix Jenkins

---

Jenkinsfile

I added comments to the Jenkinsfile (drawing heavily from spacetelescope/training-library#88), added some heading meta-info, and made all the tabs in the file 4 spaces.
Closes #455.

Add comments to Jenkinsfile

---

CHANGES.rst
setup.py

This PR updates `setup.py` and `CHANGES.rst` for the `0.21.0` release.

Release 0.21.0 [develop]

---

setup.py

Moved DEPENDENCY_LINKS to before setup() in setup.py to fix logging

---

.pyup.yml

This PR chances the frequency of pyup dependency updates from weekly to monthly.
Closes #548

Change Pyup cadence from weekly to monthly

---

environment_python_3_6.yml
requirements.txt
setup.py

Specify restriction on bokeh version to fix cron job errors

---

.pep8speaks.yml

#497 pep8speaks - Disable E501 Line Too Long error

---

CHANGES.rst
setup.py

This PR adds release notes and updates the version number for release `v0.23.0`.

Release v0.23

---

environment_python_3_6.yml
environment_python_3_7.yml
environment_python_3_8.yml

This PR updates the versions of `pandas` and `numpy` in attempt to solve the issue presented in #627.
Closes #627

Update pandas and numpy to solve cron job issues

---

docs/source/tests.rst
jwql/tests/test_bias_monitor.py

Adds unit tests for the bias monitor

Make bias monitor tests

---

CHANGES.rst
setup.py

This PR signifies the `v0.24` release into the `develop` branch

v0.24.0 Release [develop]

---

jwql/utils/credentials.py

Switch EDB MAST token authentication to use config.json

---

jwql/website/apps/jwql/templates/instrument.html

Page is currently some text with a lot of buttons. This will organize each field and the buttons in a more stylized fashion. This will take care of issue #563

Reorganize Instrument Landing Page

---

environment_python_3_6.yml
environment_python_3_7.yml
environment_python_3_8.yml
requirements.txt
setup.py

Updated django to latest version

---

environment_python_3_6.yml
environment_python_3_7.yml
environment_python_3_8.yml
requirements.txt
setup.py

Update bokeh to latest version

---

jwql/utils/constants.py
jwql/website/apps/jwql/bokeh_containers.py
jwql/website/apps/jwql/monitor_pages/__init__.py
jwql/website/apps/jwql/monitor_pages/monitor_bias_bokeh.py
jwql/website/apps/jwql/monitor_pages/yaml/monitor_bias_interface.yaml
jwql/website/apps/jwql/monitor_views.py
jwql/website/apps/jwql/templates/bias_monitor.html
jwql/website/apps/jwql/urls.py

This PR creates the Bias Monitor plots/webpage (currently only active for NIRCam).

Make Bias Monitor plots/webpage

---

CHANGES.rst
setup.py

This PR signifies release `v0.25.0`.

Release v0.25.0 [into develop]

---

jwql/website/apps/jwql/oauth.py
jwql/website/apps/jwql/views.py

This PR adds a condition in `oauth.py` which allows users running the web app locally to automatically bypass login.
Closes #675

Bypass authentication for users running web app locally

---

jwql/website/apps/jwql/monitor_pages/monitor_dark_bokeh.py

This is a small PR that adds some code to create dummy data for the dark current monitor in cases where the dark current databases are empty. Prior to these changes, if the databases were empty, JWQL would crash as it attempted to use the non-existent data to create the Bokeh plots.

Prevent dark monitor crash when database is empty

---

README.md

Forgot to change the name of the yaml files when updating/removing references to python 3.6

Updating yaml environment file names

---

jwql/website/apps/jwql/templates/base.html
jwql/website/apps/jwql/templates/instrument.html

Remove options that are not supported currently including image anomalies, unlooked images and monitors that haven't been implemented yet.

Remove Unsupported Monitors and Image View Options

---

docs/source/jwql_monitors.rst
jwql/jwql_monitors/generate_proposal_thumbnails.py
jwql/utils/constants.py
jwql/utils/utils.py
jwql/website/apps/jwql/data_containers.py
jwql/website/apps/jwql/views.py

This PR aims to improve the loading times to the web app archive pages.  Closes #676

Improve loading times for web app archive pages

---

jwql/website/apps/jwql/data_containers.py
jwql/website/apps/jwql/static/js/jwql.js
rtd_requirements.txt

This PR changes the displayed expstart when hovering over thumbnails from MJD to YYYY-MM-DD HH:MM:SS

Change expstart in thumbnail hover to more human readable format

---

jwql/website/apps/jwql/bokeh_dashboard.py

Various Updates To Dashboard

---

jwql/website/apps/jwql/templates/about.html
jwql/website/apps/jwql/templates/home.html

This PR makes changes to the about page to describe the bug/feature request instructions for users.

Add info on bug/feature requests to about page

---

jwql/edb/engineering_database.py
jwql/example_config.json
jwql/jwql_monitors/monitor_mast.py
jwql/tests/test_dark_monitor.py
jwql/tests/test_monitor_mast.py
jwql/website/apps/jwql/data_containers.py

Switch to test string for astroquery.mast queries

---

jwql/utils/constants.py
jwql/website/apps/jwql/views.py

This PR fixes an issue in which the archive webpages were not loading on the dev/test/ops servers.  It also updates `constants.py` with a newly-encountered suffix type for segmentation map files.

Fix archive webpage ajax issue

---

jwql/utils/constants.py
jwql/website/apps/jwql/bokeh_dashboard.py
jwql/website/apps/jwql/data_containers.py
jwql/website/apps/jwql/templates/api_landing.html
jwql/website/apps/jwql/templates/home.html

This is a catch-all PR that fixes various issues and makes various enhancements to the web app:
- Updates programmatic API examples to use production server (i.e. `https://jwql.stsci.edu`) instead of dev server
- Adds support for `c1d` filetypes in `utils.filename_parser()`
- Fixes bug in dashboard that was causing webpage to crash in the absence of data
- Removes unnecessary parts of docstrings in `bokeh_dashboard.py`
- Fixes bug in `data_containers.py` that was causing `get_expstart()` to crash on segmentation map files
- Updates the 'Query the archive for anomalies' header on homepage to just 'Query the archive' (since one could query for more than just anomalies)

Fix various webapp issues

---

jwql/edb/engineering_database.py
jwql/website/apps/jwql/data_containers.py
jwql/website/apps/jwql/templates/engineering_database.html

Many of the mnemonic datasets used by the EDB contain `date` and non-numerical `euvalues`.
Current approach:
* If unique possible values of `euvalues` is `> 1 & <=4` then we will plot the data.
* If unique possible values of `euvalues` is `> 4` then we will display a table
* If values are numeric, just generate the expected figure.

Plot non-numerical mnemonic dataset

---

jwql/website/apps/jwql/data_containers.py
jwql/website/apps/jwql/templates/base.html
jwql/website/apps/jwql/templates/jwqldb_table_viewer.html
jwql/website/apps/jwql/views.py
style_guide/accessibility_guidelines.md

Multiple Web Application House Keeping Items 

---

jwql/instrument_monitors/common_monitors/bad_pixel_monitor.py
jwql/instrument_monitors/common_monitors/bias_monitor.py
jwql/instrument_monitors/common_monitors/dark_monitor.py
jwql/instrument_monitors/common_monitors/readnoise_monitor.py
jwql/jwql_monitors/monitor_filesystem.py
jwql/website/apps/jwql/data_containers.py
jwql/website/apps/jwql/db.py
jwql/website/apps/jwql/monitor_pages/monitor_bad_pixel_bokeh.py
jwql/website/apps/jwql/monitor_pages/monitor_bias_bokeh.py
jwql/website/apps/jwql/monitor_pages/monitor_dark_bokeh.py
jwql/website/apps/jwql/monitor_pages/monitor_readnoise_bokeh.py
jwql/website/apps/jwql/templates/jwqldb_table_viewer.html

Addresses #891. I am looking around the web application and noticed that we have a lot of sessions that are left open after we perform queries. I am unsure if this will solve our problems immediately, but it's worth a shot.

Closing Session in build_table Function

---

jwql/website/apps/jwql/data_containers.py

Updating "Filter By" Dropdown in Archive View

---

jwql/website/apps/jwql/templates/engineering_database.html

update feature desciption on EDB page

---

.github/workflows/ci.yml
README.md
environment_python_3_9.yml

- Created 3.9 environment
- Removed support for python 3.7
- Updated README docs

Add JWQL Python 3.9 Environment

---

CHANGES.rst
setup.py

Release [main]

---

CHANGES.rst
setup.py

Release [develop]
