spacetelescope/jwql

.pep8speaks.yml
This PR adds a line to ignore `E505` (line too long) in `.pep8speaks.yml`.
=> Ignoring E505 (line too long) in pep8speaks

README.md, jwql/website/apps/jwql/templates/about.html, jwql/website/apps/jwql/templates/archive.html, jwql/website/apps/jwql/templates/base.html, jwql/website/apps/jwql/templates/dashboard.html, jwql/website/apps/jwql/templates/home.html, jwql/website/apps/jwql/templates/instrument.html, jwql/website/apps/jwql/templates/thumbnails.html, jwql/website/apps/jwql/templates/view_header.html, jwql/website/apps/jwql/templates/view_image.html, jwql/website/apps/jwql/views.py, jwql/website/jwql_proj/urls.py
This PR removes references to the term "Quicklook" from the application, as we are trying to stray away from that term and promote our acronym `JWQL`.
=> Remove "Quicklook" reference from outward-facing content

jwql/website/apps/jwql/templates/about.html, jwql/website/apps/jwql/templates/base.html
I added a "Documentation" button the top navbar in the base.html template. Maybe once the documentation fills out, we should swap out the button for a pull down menu that links to the documentation pages that are of the most interest?
=> WIP: Add documentation button to top of base.html

jwql/tests/test_utils.py, jwql/utils/utils.py, jwql/website/apps/jwql/forms.py, jwql/website/apps/jwql/static/css/jwql.css, jwql/website/apps/jwql/templates/home.html, jwql/website/apps/jwql/views.py
Introduces new form on the web app homepage that allows users to immediately search for JWST proposals or rootnames (e.g. 86600; jw86600006001_02101_00008_guider1) and easily get to the appropriate `thumbnails` or `view_image` webpage. Changes include:
- Modifying `views.home` to handle the new search form
- Adding a `forms.py` file in the web app to create and validate the search form using Django's awesome object-oriented form method
- Adding a `fileroot_parser` util to `utils.py` for convenience
I threw this together kind of quickly, with much copy-and-pasting from StackOverflow, so please let me know if anything is particularly unclear or where there are any style guide violations!
Sadly, this PR does not achieve @bourque 's bonus of accepting a list of fileroots - that is going to …
=> Homepage search form

jwql/tests/test_monitor_mast.py
This PR attempts to solve the failed `test_instrument_inventory_filtering` test in `test_monitor_mast`.
Closes #187
=> Fix test_monitor_mast

jwql/utils/utils.py, jwql/website/apps/jwql/forms.py, jwql/website/apps/jwql/templates/view_image.html, jwql/website/apps/jwql/urls.py, jwql/website/apps/jwql/views.py
This PR does the following:
- Removes `jwql` from the beginning of all URLs
- Uses regular expressions to restrict instrument input in URLs (á la @bourque)
- Makes all URLs flexible to input either capitalized or lowercase instruments
- Adds more suffixes to the list that `filename_parser` accepts
No tests yet, but I'm hoping to get to those with #220.
Closes #211.
=> Improve URLs

jwql/jwql_monitors/generate_preview_images.py
This PR updates the `generate_preview_images` module to use the new `constants.py` module to import the `NIRCAM_SHORTWAVE_DETECTORS` and `NIRCAM_LONGWAVE_DETECTORS` data.
Closes #266
=> Update generate_preview_images to use constants.py module

jwql/tests/test_api_views.py, jwql/website/apps/jwql/data_containers.py
This PR adds several tests to `test_api_views` in order to test more instruments, proposals, and filenames.  It also refactors a few of the functions in `data_containers` in order to speed them up, as I was finding some of the views to be really slow when dealing with a large amount of data.
Closes #232
=> More API views tests

README.md
This PR adds a section to the `README` that describes how to provide the `config.json` file when installing the `jwql` package.  This references the recently modified [wiki page](https://github.com/spacetelescope/jwql/wiki/Config-file), which now contains a template file.
Closes #282
=> Config file instructions

jwql/utils/utils.py
Adds a custom message to the `FileNotFoundError` that arises when the `config.json` file is missing, including a link to the new wiki page about it. (Thanks #287!)
Closes #274.
=> Add custom error message if config.json is missing

WEBPAGE_TEMPLATE.md, jwql/website/apps/jwql/data_containers.py, jwql/website/apps/jwql/templates/WEBPAGE_TEMPLATE.html, jwql/website/apps/jwql/urls.py, jwql/website/apps/jwql/views.py
My attempt to make a set of template files that a new contributor can use to get a head start developing a new web page.
I have tried to write extensive directions into a new markdown page, `WEBPAGE_TEMPLATE.md`, which should hopefully point to the right new files and functions, and explain how to use the branch as a template. Please let me know which parts of those directions is unclear!
Note that this PR merges into `upstream/webpage-template` rather than `master`. The instructions file, `WEBPAGE_TEMPLATE.md`, will need to be merged separately into `master`, but I have designed the other files to live specifically in a new `upstream/webpage-template` branch so that they can be used out-of-the-box without cluttering the existing code.
...This does mean that updates to `master` would need …
=> Webpage template branch

notebooks/integrating_auth_mast_service.ipynb
This PR adds a `jupyter` notebook with examples showing how to integrate the `auth.mast` service into a `django` web application.  Hopefully it can be useful for others at ST wishing to integrate `auth.mast` like we have done!
=> auth.mast example notebook

docs/source/database.rst, jwql/database/database_interface.py, jwql/database/reset_database.py
This PR adds a `reset_database.py` module, which will reset the database given in the `connection_string` key in the `config.json` config file.  This can be used to easily reset the development database.
=> Reset database

jwql/tests/test_utils.py
While looking at the Jenkins build for the latest pyup PR, I discovered 2 problems:
1. `test_filename_parser_whole_filesystem` in `test_utils` did not include a `FileNotFoundError` in its list of errors that are acceptable for the `xfail`
2. Perhaps more concerningly, the Jenkins build did not mark the build as a failure, despite this error
Here is the build: https://ssbjenkins.stsci.edu/blue/organizations/jenkins/STScI%2Fjwql/detail/PR-330/2/pipeline/18
This PR addresses 1, but not 2. Not sure who to ask about 2, since I thought #303 would have solved this.
=> Add FileNotFoundError to "raises" for filename_parser test

README.md, style_guide/style_guide.md
This PR updates our documentation to describe a new release-driven git workflow for the `jwql` project.  Updated documents include:
- `README.md`
- `style_guide.md`
- The wiki for [`git`/GitHub workflow](https://github.com/spacetelescope/jwql/wiki/git-&-GitHub-workflow-for-contributing)
- The wiki for [software releases](https://github.com/spacetelescope/jwql/wiki/Software-Releases)
- The wiki for [Checklist for Contributors and Reviewers of PRs](https://github.com/spacetelescope/jwql/wiki/Checklist-for-Contributors-and-Reviewers-of-Pull-Requests)
Closes #295
=> Release-driven git workflow

jwql/jwql_monitors/monitor_cron_jobs.py
This PR contains minor tweaks to `monitor_cron_jobs` to use recent updates to `logging_functions` (#350).
=> Update cron_job_monitor to use updates from logging_functions

jwql/tests/test_preview_image.py
I have been struggling with tests failing locally, and I traced it back to not enough things being deleted in the teardown script for `test_preview_image`. (It wasn't the permissions thing after all, @bourque!)
This PR:
- Adds an `if `statement to avoid errors for making the local test directory if it already exists
- Removes all files in the local test directory during teardown
- Removes all thumbnails/jpgs in the test directory on central storage during teardown (Though now I am less sure as to why having files there was causing problems... hopefully this doesn't break anything unexpected?)
- Parameterizes `test_make_image()`
=> Improve test_preview_image

README.md, codecov.yml
Closes #367.
This PR updates `codecov.yml` to:
- Have a more forgiving color code, where 0% coverage is red and 75% is green (it was previously 70 and 100!!!)
- Hopefully stop adding checks to the CI that can mark the build as failed
- Add more information about the files changed by any given PR
- Ignore data trending plot files and HTML/CSS/JS files
- Include some website files in the coverage report
=> Update Codecov settings

jwql/website/apps/jwql/data_containers.py
Closes #375.
This PR fixes the bug where the dashboard page does not load, throwing an error.
I got around it by adding checks in `data_containers/get_dashboard_components()` to only attempt to load HTML/JavaScript files from known monitors. I also added a feature to programmatically generate formatted plot names from the component files.
This means that a developer adding a new monitor to the dashboard page will need to explicitly add the monitor to `name_dict` in `data_containers/get_dashboard_components()` for it to be loaded. However, once a monitor is added to that dictionary, every plot in the output directory for that monitor will be shown.
=> Fix dashboard

JenkinsfileRT
The node label `linux-stable` is only honored on the CI system. The periodically scheduled RT job will continue to fail until the node label is changed.
=> Adjust Jenkins node label to allow execution on RT system.

jwql/tests/test_calculations.py
This PR relaxes the tolerances for the fitting results for the `test_gaussian1d_fit` functions. The previous tolerances were too tight and causing Jenkins to fail.
Closes #411.
=> Relax requirements for gaussian 1d test

jwql/tests/test_pipeline_tools.py
This PR modifies `test_pipeline_tools` in order to get the tests within to pass in a Python 3.5 environment.
Closes #398
=> Fix test_get_pipeline_steps for python 3.5

Jenkinsfile
Addresses an issue found in #398 (this does not address the specific failing test, only the issue where the failing test is not failing the build)
Pytest failures are not failing the build for python 3.5. This was due to the latest version of pytest for python 3.5 is pytest 3.8.1. Junit family config option was added in pytest 4.2 which is needed to make the pytest junit xml ingestible by jenkins.
Added sed command to (hopefully) manually strip unknown attributes from the xml to please jenkins.
=> Add sed command to remove invalid attrs from junit xml

jwql/tests/test_pipeline_tools.py
This PR updates `test_pipeline_tools.test_completed_pipeline_steps` to avoid testing ordered dictionaries and corresponding issues with Python 3.5 Jenkins builds.  A continuation of #414.
=> Fix test_completed_pipeline_steps for python 3.5

jwql/website/apps/jwql/oauth.py
This PR fixes a bug wherein the web app crashes on the dev server when trying to redirect to the previous page after login; if the user has not yet visited another page within the web app, there exists no view for the previous page.
Addresses concerns in #406
=> Fix web app redirect issues

jwql/tests/test_plotting.py
I was inspired (frustrated?) by #425 to write up a quick test that will fail if the Bokeh versions in our HTML templates don't match our environment.
(This will fail Jenkins until #429 is merged.)
=> Add bokeh version test

jwql/tests/test_database_interface.py
This PR adds/improves tests in `test_database_interface`, including:
- Updating `test_anomaly_records` to test the addition of a record with a specific rootname
- Adding test that ensures all tables defined in `database_interface` actually exist in the database
- Adding tests for ORM factory functions
- Adding test for establishing connection to the database
Closes #433
=> Improve test_database_interface

jwql/website/apps/jwql/static/css/jwql.css
This PR fixes a bug that was causing the JWQL version number in the footer of the web app to fall below the footer itself.
Simple fix. I increased the size of the text box containing the version number and it returned to the footer where it should be.
Closes #435
=> Increase width of footer object containing jwql version number

environment_python_3_6.yml, jwql/website/apps/jwql/views.py, jwql/website/jwql_proj/settings.py
This PR provides various changes to get the web app working with `django` version 2.2. 
The new version requires the existence of a define `django.template.backends.django.DjangoTemplates` `TEMPLATE`.  Also, some `not_found` requests now also require additional parameters such as `exception`, which have been wrapped up in a `*args` parameter.
=> Update web app to use django 2.2

jwql/database/monitor_table_definitions/fgs/fgs_dark_dark_current.txt, jwql/database/monitor_table_definitions/miri/miri_dark_dark_current.txt, jwql/database/monitor_table_definitions/nircam/nircam_dark_dark_current.txt, jwql/database/monitor_table_definitions/niriss/niriss_dark_dark_current.txt, jwql/database/monitor_table_definitions/nirspec/nirspec_dark_dark_current.txt
This PR fixes typos in some of the column names of the *dark_dark_current database tables used by the dark current monitor. Prior to this fix, one of the column names was "guass_peak" when it should have been "gauss_peak".
Closes #452
=> Fix guass_peak typo in column names

README.md
This PR updates the `README` to include a section on installing the `jwql` package for users (which is simply a `pip install jwql`).
Even with the capability to `pip install jwql`, the install instructions for contributors remains the same, as to encourage a `python setup.py develop` so that `jwql` is installed to a `$PATH` that makes it easy to test code changes.
Also included is a small update to the list of current dev members and acknowledgements. 
Closes #441
=> Updated README to include pip install instructions

environment_python_3_6.yml, requirements.txt, setup.py
This PR updates the `environment_python_3.6.yml`/`jwql-3.6` `conda` environment with some small tweaks to make sure the environment works on a linux distribution. I had run into some issues with the current environment when trying to install on a linux box.
=> Updates to 3.6 conda environment to get it working on a linux distro

environment_python_3_5.yml, environment_python_3_6.yml, requirements.txt, setup.py
This PR makes changes to the `jwql` `conda` environments, `setup.py`, and `requirements.txt` so that they are all consistent and only include those dependencies that are explicitly used within the `jwql` package.
Closes #481
=> Simplify conda environments

jwql/database/database_interface.py
This PR fixes a small typo in the `status` field of the `monitor` database table.  This typo has been causing errors in the `dark_monitor` when it completes and tries to update this table.
=> Fix typo in monitor table

environment_python_3_6.yml, requirements.txt
This PR rolls back the `bokeh` version in the conda environment from version 1.4 to 1.3 to avoid errors described in #525 
Closes #525
=> Rollback Bokeh to version 1.3

environment_python_3_6.yml
This PR fixes a small typo that was causing the wrong version of the ``jwst`` package to be installed when using the environment file. Replacing the # symbol with the @ symbol allows the specified version to be installed. I updated the version to the latest released version. I also updated the version of ``asdf`` to match that required by 0.15.0 of the pipeline.
=> Fix typo in jwst installation version tag

style_guide/README.md
The location of numpy's docstring guide has changed; this commit updates the URL to the new location.
=> Fix link to numpy docstring guide

jwql/website/apps/jwql/views.py
This PR updates the JDox links on our instrument pages to point to the current top-level pages. The links we previously had in there were no longer correct.
=> Update top level instrument JDox links

jwql/instrument_monitors/common_monitors/dark_monitor.py
This PR fixes an issue with the most_recent_search() method that was first discovered when working on #612 . The database query used to find the date of the most recent run of the monitor for a given aperture was not working correctly. This fix updates the method to work in a similar way to the corresponding function in the bad pixel monitor. 
A quick test with a reset and custom-populated dark monitor database table showed that the new code returns the expected value.
Resolves #637
=> Fix dark monitor database query

jwql/website/apps/jwql/monitor_pages/monitor_readnoise_bokeh.py
This simple edit should fix the issue of the readnoise monitor accessing the database when just starting the web app, which was resulting in "hanging" database processes when running the web app. 
Now, it only accesses the database when you actually go to the readnoise monitor webpage and the database processes go away when you navigate to another monitor webpage, which I verified is the same behavior of other monitor webpages (e.g. the bad pixel webpage).
=> Fix readnoise webpage hanging issue

jwql/website/apps/jwql/bokeh_containers.py, jwql/website/apps/jwql/monitor_pages/monitor_readnoise_bokeh.py, jwql/website/apps/jwql/monitor_pages/yaml/monitor_readnoise_interface.yaml
This PR modifies the creation of the readnoise monitor webpage to speed up the page load time. 
While it adds some repetition to the yaml file (i.e. the same issue noted by Matthew in this bias monitor PR https://github.com/spacetelescope/jwql/pull/680), it speeds up the page load time significantly, from ~12s to ~4s for NIRCam (the other instruments load almost instantly regardless).
I also made some modifications to the page layout to make the readnoise difference image less blurry and the page more responsive in general.
The new readnoise monitor page:
=> Speed up readnoise monitor webpage

jwql/utils/constants.py
This PR adds support for stage 3 WFS&C and additional AMI products in the filename parser. 
These types of products don't currently live in our JWQL filesystem (and thus, `test_filename_parser_whole_filesystem` passes regardless of this PR), but they will be eventually once we sync up with MAST. 
I've successfully tested it on the example names given [here](https://innerspace.stsci.edu/pages/viewpage.action?spaceKey=SCSB&title=JWST+Science+Data+Products) for these product types.
=> Fix filename parsing for WFS&C and AMI products

jwql/instrument_monitors/pipeline_tools.py
This PR updates the call to the JWST pipeline RSCD step, which changed naming formats to be consistent with the other pipeline steps.
I didn't see any other codes directly calling this step, so only `pipeline_tools` was updated.
=> Update pipeline rscd step call

jwql/instrument_monitors/common_monitors/dark_monitor.py
Resolves #618 
This PR updates the dark monitor for the case where the MAST query returns enough data to proceed, but the identified files are not present in the filesystem. With this update, if the MAST query returns enough new files to proceed, the dark monitor will search the filesystem. If after the search, enough of the new files are present (relative to the required minimum number), then the dark monitor will run. If enough of the files identified by MAST are missing in the filesystem that the number of files is less than the threshold, the monitor will be skipped.
=> Dark monitor exits gracefully when not enough files in filesystem

jwql/instrument_monitors/common_monitors/readnoise_monitor.py
This PR fixes the error handling in the Readnoise Monitor when no matching CRDS reffile can be found.
=> Fix missing reffile error handling in Readnoise Monitor

environment_python_3_7.yml, environment_python_3_8.yml
Remove need for astroconda channel by pip installing packages that were previously installed with astroconda.
=> Remove need for astroconda channel

jwql/instrument_monitors/common_monitors/bad_pixel_monitor.py
This PR adds some documentation to the instrument monitors describing the algorithms used. Documentation for the bad pixel monitor has been added to the docstring for the module, so that it will show up in the API documentation on readthedocs.
=> Algorithm documentation

jwql/website/apps/jwql/monitor_pages/monitor_bias_bokeh.py, jwql/website/apps/jwql/monitor_pages/monitor_readnoise_bokeh.py
This PR should fix https://github.com/spacetelescope/jwql/issues/834 by making the scale limits calculation for the bias and readnoise monitors robust to missing data.
The data that caused this issue shouldn't exist in flight - it was a subarray with incorrect header info calling it full frame, which doesnt have multiple output channels so those database columns were blank for it, causing the crash.
=> Made plotting limits robust to missing data

jwql/website/apps/jwql/data_containers.py, jwql/website/apps/jwql/static/js/jwql.js, jwql/website/apps/jwql/templates/view_header.html, jwql/website/apps/jwql/templates/view_image.html, jwql/website/apps/jwql/urls.py, jwql/website/apps/jwql/views.py
The "View Header" button now points to a page that shows the header of the image based on which radio button is clicked (rather than always showing the header of the rate image). The header page has the file type in the title and URL looks like `FGS/jw86700012001_02101_00001_guider1_rate/header/` or `FGS/jw86700012001_02101_00001_guider1_uncal/header/`.
I also did some random clean up:
- In `change_filetype` function in `jwql.js`, I added some missing semi-colons
- In `change_filetype` function in `jwql.js`, I removed or commented out lines that referenced code in `view_image.html` that had already been removed or commented out, which were causing errors. 
- In `view_image.html`, cleaned up some indentations that were off
Closes #803
=> View header for chosen file type

jwql/utils/constants.py, jwql/website/apps/jwql/bokeh_containers.py
Resolves #872 
This PR fixes a couple of small bugs in the dark monitor that were causing it to crash for instruments other than NIRCam.
=> Allow dark monitor to work for all instruments

.gitignore, jwql/utils/constants.py, jwql/utils/utils.py
In particular, this updates the instrument-specific "Documentation" links, as well as the JDox URL returned on an exception from utils.py filename_parser().
Closes #889
=> Updated JDOX links so they don't produce 404 errors
